server.address=127.0.0.1
server.port=8083

spring.datasource.url=${NOTIFICATION_DB_URL:jdbc:postgresql://localhost:5433/notifications_db}
spring.datasource.username=${NOTIFICATION_DB_USERNAME:booking}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD:booking_local}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:roombook}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:roombook_local}
spring.rabbitmq.connection-timeout=3s
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=1
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.default-requeue-rejected=false

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
