server.address=0.0.0.0
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/notifications_db
spring.datasource.username=booking
spring.datasource.password=booking_local

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=roombook
spring.rabbitmq.password=${RABBITMQ_PASSWORD:roombook_local}
spring.rabbitmq.connection-timeout=3s
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=1
spring.rabbitmq.listener.simple.prefetch=10
spring.rabbitmq.listener.simple.default-requeue-rejected=false

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.hostname=notification-service

spring.security.oauth2.client.registration.profile-service.provider=keycloak
spring.security.oauth2.client.registration.profile-service.client-id=notification-service
spring.security.oauth2.client.registration.profile-service.client-secret=${NOTIFICATION_SERVICE_CLIENT_SECRET}
spring.security.oauth2.client.registration.profile-service.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/realms/roombook/protocol/openid-connect/token

spring.grpc.client.channel.profile-service.target=static://profile-service:9090

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans
