server.address=127.0.0.1
server.port=8082

spring.datasource.url=${ROOM_DB_URL:jdbc:postgresql://localhost:5433/rooms_db}
spring.datasource.username=${ROOM_DB_USERNAME:booking}
spring.datasource.password=${ROOM_DB_PASSWORD:booking_local}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/roombook}
