server.address=0.0.0.0
server.port=8084

spring.datasource.url=jdbc:postgresql://postgres:5432/profiles_db
spring.datasource.username=booking
spring.datasource.password=booking_local

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/roombook
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/roombook/protocol/openid-connect/certs

spring.grpc.server.address=0.0.0.0

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.hostname=profile-service

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans
