spring.application.name=discovery-server
server.address=127.0.0.1
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
